const path = require('path')
const fs = require('fs-extra')
const glob = require('glob')
const config = {
  assetInputFolder: `${__dirname}/dist/_nuxt`,
  assetOutputFolder:`${__dirname}/demo/views/assets/_nuxt`,
  contentInputFolder: `${__dirname}/dist/`,
  contentOutputFolder: `${__dirname}/demo/views/components/gnd/`,
  routerFile: `${__dirname}/demo/views/docs-router.liquid`,
  spaceId: 52487
}

const version = Date.now()

const RenderingServiceHelper = {
  init: () => {
    RenderingServiceHelper.generateRouter()
    RenderingServiceHelper.generateLiquids()
    RenderingServiceHelper.generateAssets()
  },
  generateRouter: () => {
    let routes = []
    glob(`${__dirname}/dist/**/*.html`, { ignore: '**/dist/*.html' },
      (err, files) => {
        files.forEach((file) => {
          let requestRoute = path.dirname(file).replace(config.contentInputFolder, '')
          let output = RenderingServiceHelper.generateLiquidOutputPaths(file)
          let pathToLiquid = output.folder.replace(config.contentOutputFolder, '') + '/' + RenderingServiceHelper.replaceAll(output.originalFilename, '-', '_')
        
          routes.push(`
  {% when '/${requestRoute}' %}
    {% include 'gnd/${pathToLiquid}' %}`)
        })

        let routerTemplate = `{% comment %} THIS FILE IS AUTOGENERATED - DO NOT CHANGE! {% endcomment %}
{{spaceless}}
{% case request.path %}${routes.join('')}
  {% else %}
    {% flow show_404 %}
{% endcase %} 
{{endspaceless}}`

        fs.ensureDirSync(path.dirname(config.routerFile))
        
        fs.writeFile(config.routerFile, routerTemplate, (err) => {
          if (err) throw err
        })
      }
    )
  },
  generateLiquids: () => {
    glob(`${__dirname}/dist/**/*.html`, { ignore: '**/dist/*.html' },
      (err, files) => {
        files.forEach((input) => {
          let output = RenderingServiceHelper.generateLiquidOutputPaths(input)

          fs.ensureDirSync(output.folder)

          fs.readFile(input, { encoding: 'utf8' }, (err, data) => {
            data = RenderingServiceHelper.resolveAssets(data)
            data = RenderingServiceHelper.addVersionParam(data)

            fs.writeFile(path.join(output.folder, output.filename), data, (err) => {
              if (err) throw err
            })
          })
        })
      }
    )
  },
  generateAssets: () => { 
    glob(`${__dirname}/dist/_nuxt/*.js`, (err, files) => {
      files.forEach((file) => {
        let outputFolder = path.dirname(file).replace(config.assetInputFolder, config.assetOutputFolder)
        let outputFilename = path.basename(file)
        
        fs.ensureDirSync(outputFolder)

        fs.readFile(file, { encoding: 'utf8' }, (err, data) => {
          
          data = RenderingServiceHelper.resolveAssets(data)
          data = RenderingServiceHelper.addVersionParam(data)

          fs.writeFile(path.join(outputFolder, outputFilename), data, (err) => {
            if (err) throw err
          })
        })
      })
    })
  },
  generateLiquidOutputPaths: (file) => {
    let absoluteOutputFilepath = path.dirname(file).replace(config.contentInputFolder, config.contentOutputFolder)
    let originalFilename = path.basename(absoluteOutputFilepath)
    let filename = '_' + RenderingServiceHelper.replaceAll(originalFilename, '-', '_') + '.liquid'
    let folder = path.dirname(absoluteOutputFilepath)

    return {
      folder,
      originalFilename,
      filename
    }
  },
  addVersionParam: (data) => {
    return RenderingServiceHelper.replaceAll(data, `.js"`, `.js?v=${version}"`)  
  },
  resolveAssets: (data) => {
    return RenderingServiceHelper.replaceAll(data, '/_nuxt/', '//a.storyblok.com/t/' + config.spaceId + '/assets/_nuxt/')
  },
  replaceAll(target, search, replacement) {
    return target.replace(new RegExp(search, 'g'), replacement);
  }
}

RenderingServiceHelper.init()